# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 08:03
from __future__ import unicode_literals

import Pentagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0002_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Pentagram.models.photos_directory),
        ),
    ]
